# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# pylint: disable=unused-argument
"""tvm.contrib.msc.core.tools.base_tool"""

import os
import copy
import logging
from functools import wraps
from itertools import product
from typing import List, Iterable, Any, Tuple, Dict
import numpy as np

import tvm
from tvm.contrib.msc.core.ir import MSCGraph, MSCJoint, MSCTensor
from tvm.contrib.msc.core.utils.namespace import MSCMap, MSCKey, MSCFramework
from tvm.contrib.msc.core import utils as msc_utils


class ToolType(object):
    """Enum all msc tool typs"""

    BASE = "base"
    PRUNE = "prune"
    QUANTIZE = "quantize"
    DISTILL = "distill"
    DEBUG = "debug"

    @classmethod
    def all_types(cls) -> List[str]:
        return [cls.PRUNE, cls.QUANTIZE, cls.DISTILL, cls.DEBUG]


class Strategy(object):
    """Strategy for process tensor

    Parameters
    ----------
    name: str
        The name.
    stage: str
        The init stage
    """

    def __init__(self, name: str, stage: str = "default"):
        self._name = name
        self._stage = stage
        self._executors = {}

    def __str__(self):
        return "{}({}): {}".format(self._name, self._stage, self._executors)

    def __call__(self, *args, **kwargs) -> Any:
        return self.execute(*args, **kwargs)

    def execute(self, *args, **kwargs) -> Any:
        """Execute the strategy

        Parameters
        ----------
        args: list<Any>
            The arguments for run method.
        kwargs: dict<Any>
            The key word arguments for run method.

        Returns
        -------
        plan or tensot:
           The plan generated by method or processed tensor.
        """

        method, config = self.get_executor()
        kwargs.update({k: v for k, v in config.items() if k not in kwargs})
        return method(*args, **kwargs)

    def add_executor(self, stage: str, method: callable, config: dict):
        """Add a executor to strategy

        Parameters
        ----------
        stage: str
            The mark of the executor
        method: callable
            The method to process tensor.
        method_config: dict
            The method config.
        """

        self._executors[stage] = (method, config)
        if not self._stage:
            self._stage = stage

    def change_stage(self, stage: str):
        """Change the stage of strategy"""

        self._stage = stage

    def get_config(self, key: str, default: Any) -> Any:
        """Get the value in config"""

        return self._executors[self._stage][1].get(key, default)

    def get_executor(self) -> Tuple[callable, dict]:
        """Get executor of current stage

        Returns
        -------
        executor: tuple<callable, dict>
           The method and config to execute strategy
        """

        return self._executors[self._stage]

    def copy(
        self,
        name: str = None,
        stage: str = None,
        methods: Dict[str, callable] = None,
        configs: Dict[str, dict] = None,
    ):
        """Copy a strategy

        Parameters
        ----------
        name: str
            The name for new strategy
        stage: str
            The init stage for new strategy
        methods: dict<str, callable>
            The methods of new executors.
        configs: dict<str,dict>
            The method config of new executors.

        Returns
        -------
        new_strategy: Strategy
           The copied strategy
        """

        methods = methods or {}
        configs = configs or {}
        strategy = Strategy(name or self._name, stage or self._stage)
        for st_name, (method, config) in self._executors.items():
            new_method = methods.get(st_name, method)
            new_config = configs.get(st_name, {})
            new_config.update({k: v for k, v in config.items() if k not in new_config})
            strategy.add_executor(st_name, new_method, new_config)
        return strategy


class BaseTool(object):
    """Basic tool of MSC

    Parameters
    ----------
    plan_file: str
        The plan file path.
    strategy: dict
        The strategy of the tool.
    workspace: MSCDirectory
        The workspace of the tool.
    options: dict
        The extra options for the tool
    verbose_step: int
        The verbose interval step.
    logger: logging.Logger
        The logger
    """

    def __init__(
        self,
        plan_file: str,
        strategy: dict,
        workspace: msc_utils.MSCDirectory,
        options: dict = None,
        verbose_step: int = 50,
        logger: logging.Logger = None,
    ):
        self.setup(options)
        if os.path.isfile(plan_file):
            self._plan = msc_utils.load_dict(plan_file)
        else:
            self._plan = {}
        self._strategys = self._parse_strategy(msc_utils.copy_dict(strategy))
        self._workspace = workspace
        self._verbose_step = verbose_step
        self._logger = logger or msc_utils.get_global_logger()
        init_title = "{}.INIT ({})".format(self.tool_type().upper(), self.framework())
        init_info = {
            "style": self.tool_style(),
            "strategys": "; ".join(["{}({})".format(k, v) for k, v in self._strategys.items()]),
            "options": self._options,
            "verbose_step": self._verbose_step,
            "planed_num": len(self._plan),
        }
        self._logger.info(msc_utils.msg_block(init_title, init_info))
        if self._plan:
            self._logger.debug(
                msc_utils.msg_block("{}.PLAN".format(self.tool_type().upper()), self._plan)
            )

    def setup(self, options: dict, stage: str = "default"):
        """Setup the tool

        Parameters
        ----------
        options: dict
            The options for setup the tool
        stage: str
            The init stage.
        """

        self._options = options or {}
        self._tensor_status = {}
        self._enabled, self._is_training = True, True
        self._graphs, self._weights = [], []
        self._weight_names = set()
        self._graph_id, self._forward_cnt = 0, 0
        self._stage = stage

    def change_stage(self, stage: str):
        """Change the stage of tools and strategy"""

        self._stage = stage
        for strategy in self._strategys.values():
            strategy.change_stage(stage)

    def load_graphs(
        self, graphs: List[MSCGraph], weights: List[Dict[str, tvm.nd.array]]
    ) -> Tuple[List[MSCGraph], List[Dict[str, tvm.nd.array]]]:
        """Load the graphs and weights

        Parameters
        ----------
        graphs: list<MSCgraph>
            The msc graphs.
        weights: list<dic<str, tvm.nd.array>>
            The weights

        Returns
        -------
        graphs: list<MSCgraph>
            The msc graphs.
        weights: list<dic<str, tvm.nd.array>>
            The weights
        """

        self._forward_cnt = 0
        self._tensor_status = {}
        self._graphs = graphs
        self._weights = weights
        self._weight_names = set()
        for sub_weights in self._weights:
            self._weight_names |= set(sub_weights.keys())
        return self._graphs, self._weights

    def execute_before_build(self, *args, **kwargs):
        """Execute before model build

        Parameters
        ----------
        args: list<Any>
            The arguments for model build.
        kwargs: dict<Any>
            The key word arguments for model build.
        """

        if self._enabled:
            self._graph_id = self._infer_graph_id(kwargs)
            self._logger.debug(
                "<{}> before build graph[{}]({})".format(
                    self.tool_type(), self._graph_id, "train" if self._is_training else "eval"
                )
            )
            self._execute_before_build(*args, **kwargs)

    def _execute_before_build(self, *args, **kwargs):
        """Execute before model build

        Parameters
        ----------
        args: list<Any>
            The arguments for model build.
        kwargs: dict<Any>
            The key word arguments for model build.
        """

        return None

    def execute_after_build(self, output: Any) -> Any:
        """Execute after model build

        Parameters
        ----------
        output: Any
            The output reference of the model.

        Returns
        -------
        output: Any
           The modified output reference.
        """

        if self._enabled:
            output = self._execute_after_build(output)
            self._logger.debug(
                "<{}> after build graph[{}]({})".format(
                    self.tool_type(), self._graph_id, "train" if self._is_training else "eval"
                )
            )
        return output

    def _execute_after_build(self, output: Any) -> Any:
        """Execute after model build

        Parameters
        ----------
        output: Any
            The output reference of the model.

        Returns
        -------
        output: Any
           The modified output reference.
        """

        return output

    def execute_before_forward(self, *args, **kwargs):
        """Execute before model forward

        Parameters
        ----------
        args: list<Any>
            The arguments for model forward.
        kwargs: dict<Any>
            The key word arguments for model forward.
        """

        if self._enabled:
            self._graph_id = self._infer_graph_id(kwargs)
            if self.should_log():
                self._logger.debug(
                    "<{}> start graph[{}] forward[{}]".format(
                        self.tool_type(), self._graph_id, self._forward_cnt
                    )
                )
            self._execute_before_forward(*args, **kwargs)

    def _execute_before_forward(self, *args, **kwargs):
        """Execute before model forward

        Parameters
        ----------
        args: list<Any>
            The arguments for model forward.
        kwargs: dict<Any>
            The key word arguments for model forward.
        """

        return None

    def execute_after_forward(self, output: Any) -> Any:
        """Execute after model forward

        Parameters
        ----------
        output: Any
            The output reference of the model.

        Returns
        -------
        output: Any
           The modified output reference.
        """

        if self._enabled:
            output = self._execute_after_forward(output)
            if self.should_log():
                self._logger.debug(
                    "<{}> end graph[{}] forward[{}]".format(
                        self.tool_type(), self._graph_id, self._forward_cnt
                    )
                )
            self._forward_cnt += 1
        return output

    def _execute_after_forward(self, output: Any) -> Any:
        """Execute after model forward

        Parameters
        ----------
        output: Any
            The output reference of the model.

        Returns
        -------
        output: Any
           The modified output reference.
        """

        return output

    def process_tensor(self, tensor: Any, name: str, consumer: str, phase: str) -> Any:
        """Process tensor

        Parameters
        -------
        tensor: Any
            Tensor in framework
        name: str
            The name of the tensor.
        consumer: str
            The name of the consumer.
        phase: str
            The phase mark teacher| student| null

        Returns
        -------
        tensor: Any
            The processed tensor.
        """

        edge_id = self.to_edge_id(name, consumer)
        strategy = self._get_strategy(name, consumer)
        if edge_id not in self._tensor_status:
            self._tensor_status[edge_id] = {}
        if "process" not in self._tensor_status[edge_id]:
            self._tensor_status[edge_id]["process"] = self._check_tensor(
                name, consumer, phase, strategy
            )
            self._logger.debug(
                "Update tensor status(process) {}: {}".format(edge_id, self._tensor_status[edge_id])
            )
        if not self._tensor_status[edge_id]["process"]:
            return tensor
        return self._process_tensor(tensor, name, consumer, phase, strategy)

    def _check_tensor(self, name: str, consumer: str, phase: str, strategy: Strategy) -> bool:
        """Check if the tensor should be processed

        Parameters
        -------
        name: str
            The name of the tensor.
        consumer: str
            The name of the consumer.
        phase: str
            The phase mark teacher| student| null
        strategy: Strategy
            The strategy for the tensor

        Returns
        -------
        vaild: bool
            Whether to process the tensor.
        """

        return True

    def _process_tensor(
        self, tensor: Any, name: str, consumer: str, phase: str, strategy: Strategy
    ) -> Any:
        """Process tensor

        Parameters
        -------
        tensor: Any
            Tensor in framework
        name: str
            The name of the tensor.
        consumer: str
            The name of the consumer.
        phase: str
            The phase mark teacher| student| null
        strategy: Strategy
            The strategy for the tensor

        Returns
        -------
        tensor: Any
            The processed tensor.
        """

        return tensor

    def visualize(self, visual_dir: msc_utils.MSCDirectory):
        """Visualize MSCGraphs

        Parameters
        -------
        visual_dir: MSCDirectory
            Visualize path for saving graph
        """

        return

    def update_plan(self, plan: dict):
        """Update the plan

        Parameters
        ----------
        plan: dict
            The new plan.
        """

        self._plan.update(plan)

    def get_plan(self) -> dict:
        """Get the plan"""

        return self._plan

    def enable(self):
        """Enable the tool"""

        self._enabled = True

    def disable(self):
        """Disable the tool"""

        self._enabled = False

    def train(self):
        """Set the tool to train mode"""

        self._is_training = True

    def eval(self):
        """Set the tool to eval mode"""

        self._is_training = False

    def to_edge_id(self, name: str, consumer: str) -> str:
        """Concat name to unique id

        Parameters
        ----------
        name: str
            The name of tensor.
        consumer: str
            The name of consumer.

        Returns
        -------
        edge_id: str
           The unique name of edge.
        """

        return "{}-c-{}".format(name, consumer)

    def from_edge_id(self, edge_id: str) -> Tuple[str]:
        """Split name from unique id

        Parameters
        ----------
        edge_id: str
           The unique name of edge.

        Returns
        -------
        name: str
            The name of tensor.
        consumer: str
            The name of consumer.
        """

        return edge_id.split("-c-")

    def is_weight(self, name: str) -> bool:
        """Check if the tensor is weight

        Parameters
        ----------
        name: str
           The name of tensor.

        Returns
        -------
        is_weight: bool
            Whether the name is weight.
        """

        return name in self._weight_names

    def should_log(self) -> bool:
        """Check if should log

        Returns
        -------
        should_log: bool
           Whether should log.
        """

        return self._forward_cnt % self._verbose_step == 0

    def _infer_graph_id(self, kwargs: dict) -> int:
        """Infer graph id from kwargs

        Parameters
        ----------
        kwargs: dict
           The kwargs for execute.
        """

        if "graph_name" in kwargs:
            for idx, g in enumerate(self._graphs):
                if g.name == kwargs["graph_name"]:
                    return idx
        return kwargs.get("graph_id", 0)

    def get_nodes(self) -> Iterable[MSCJoint]:
        """Get all the nodes in the graphs.

        Returns
        -------
        nodes: generator<MSCJoint>
            The generator of nodes.
        """

        for g in self._graphs:
            for n in g.get_nodes():
                yield n

    def find_node(self, name: str) -> MSCJoint:
        """Find node by name.

        Parameters
        ----------
        name: string
            The name of the node.

        Returns
        -------
        node: MSCJoint
            The found node.
        """

        for g in self._graphs:
            if g.has_node(name):
                return g.find_node(name)
        raise Exception("Can not find node {} from graphs".format(name))

    def find_tensor(self, name: str) -> MSCTensor:
        """Find tensor by name.

        Parameters
        ----------
        name: string
            The name of the tensor.

        Returns
        -------
        node: MSCTensor
            The found tensor.
        """

        for g in self._graphs:
            if g.has_tensor(name):
                return g.find_tensor(name)
        raise Exception("Can not find tensor {} from graphs".format(name))

    def find_producer(self, name: str) -> MSCJoint:
        """Find producer by tensor_name .

        Parameters
        ----------
        name: string
            The name of the tensor.

        Returns
        -------
        node: MSCJoint
            The found prducer.
        """

        for g in self._graphs:
            if g.has_tensor(name):
                return g.find_producer(name)
        raise Exception("Can not find producer of {} from graphs".format(name))

    def find_consumers(self, name: str) -> List[MSCJoint]:
        """Find consumers by tensor_name.

        Parameters
        ----------
        name: string
            The name of the tensor.

        Returns
        -------
        node: list<MSCJoint>
            The found consumers.
        """

        for g in self._graphs:
            if g.has_tensor(name):
                return g.find_consumers(name)
        raise Exception("Can not find consumers of {} from graphs".format(name))

    def get_data(self, name: str) -> np.ndarray:
        """Get the data by name

        Parameters
        -------
        name: str
            The tensor name

        Returns
        -------
        data: np.ndarray
            The data.
        """

        for sub_weights in self._weights:
            if name in sub_weights:
                return msc_utils.cast_array(sub_weights[name])
        raise Exception("Can not find data " + str(name))

    def _parse_strategy(self, strategy_list: dict):
        """Parse the strategy to get valid strategy

        Parameters
        -------
        strategy_list: dict
            The given strategy

        Returns
        -------
        strategys: dict<str, Strategy>
            The parsed strategy.
        """

        strategys = {}
        assert isinstance(strategy_list, list) and all(
            isinstance(s, dict) for s in strategy_list
        ), "Strategy should be given as list of dict"
        for stra in strategy_list:
            method_cls_name = stra.pop("method_cls") if "method_cls" in stra else "default"
            method_cls = msc_utils.get_registered_tool_method(
                self.framework(), self.tool_type(), method_cls_name
            )
            default_cls = msc_utils.get_registered_tool_method(
                MSCFramework.MSC, self.tool_type(), method_cls_name
            )
            method = stra.pop("method") if "method" in stra else "default"
            method = (
                getattr(method_cls, method)
                if hasattr(method_cls, method)
                else getattr(default_cls, method)
            )
            stage = stra.pop("stage") if "stage" in stra else "default"
            if "op_types" in stra:
                op_types = stra.pop("op_types")
                if "tensor_types" in stra:
                    tensor_types = stra.pop("tensor_types")
                else:
                    tensor_types = ["input", "output", "weight"]
                for s_type, t_type in product(op_types, tensor_types):
                    mark = "{}.{}".format(s_type, t_type)
                    if mark not in strategys:
                        strategys[mark] = Strategy(mark, self._stage)
                    strategys[mark].add_executor(stage, method, copy.deepcopy(stra))
            elif "op_names" in stra:
                op_names = stra.pop("op_names")
                if "tensor_types" in stra:
                    tensor_types = stra.pop("tensor_types")
                else:
                    tensor_types = ["input", "output", "weight"]
                for s_name, t_type in product(op_names, tensor_types):
                    mark = "{}.{}".format(s_name, t_type)
                    if mark not in strategys:
                        strategys[mark] = Strategy(mark, self._stage)
                    strategys[mark].add_executor(stage, method, copy.deepcopy(stra))
            else:
                if "default" not in strategys:
                    strategys["default"] = Strategy("default", self._stage)
                strategys["default"].add_executor("default", method, copy.deepcopy(stra))
        return strategys

    def _get_strategy(self, name: str, consumer: str) -> dict:
        """Get the method by name

        Parameters
        -------
        name: str
            The tensor name.
        consumer: str
            The name of the consumer.

        Returns
        -------
        method: callable
            The method.
        """

        if consumer == "exit":
            producer = self.find_producer(name)
            name_refs = [producer.name + ".output", producer.optype + ".output"]
        else:
            suffix = "weight" if self.is_weight(name) else "input"
            consumer = self.find_node(consumer)
            name_refs = [consumer.name + "." + suffix, consumer.optype + "." + suffix]
        for n in name_refs:
            if n in self._strategys:
                return self._strategys[n]
        return self._strategys["default"]

    @classmethod
    def tool_type(cls):
        return ToolType.BASE

    @classmethod
    def framework(cls):
        return MSCFramework.MSC

    @classmethod
    def tool_style(cls):
        return "base"
