# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# pylint: disable=unused-argument
"""tvm.contrib.msc.core.tools.base_tool"""

import os
import copy
import logging
from itertools import product
from typing import List, Iterable, Any, Tuple, Dict
import numpy as np

import tvm
from tvm.contrib.msc.core.ir import MSCGraph, MSCJoint, MSCTensor
from tvm.contrib.msc.core.utils.namespace import MSCFramework
from tvm.contrib.msc.core import utils as msc_utils


class ToolType(object):
    """Enum all msc tool types"""

    BASE = "base"
    PRUNER = "pruner"
    QUANTIZER = "quantizer"
    DISTILLER = "distiller"
    TRACKER = "tracker"
    ALL = [PRUNER, QUANTIZER, DISTILLER, TRACKER]

    @classmethod
    def all_types(cls) -> List[str]:
        return cls.ALL


class Strategy(object):
    """Strategy for process tensor

    Parameters
    ----------
    name: str
        The name.
    stage: str
        The init stage
    """

    def __init__(self, name: str, stage: str = "default"):
        self._name = name
        self._stage = stage
        self._executors = {}

    def __str__(self):
        return "{}({}) ".format(self._name, self._stage) + "; ".join(
            ["E[{}]:{} -> {}".format(k, v[1], v[0]) for k, v in self._executors.items()]
        )

    def inspect(self) -> dict:
        """Get inspect of strategy

        Returns
        -------
        inspect: dict
           The inspect of the strategy.
        """

        return {
            stage: "{}({})".format(method, config)
            for stage, (method, config) in self._executors.items()
        }

    def __call__(self, *args, **kwargs) -> Any:
        return self.apply(*args, **kwargs)

    def apply(self, *args, **kwargs) -> Any:
        """Apply the strategy

        Parameters
        ----------
        args: list<Any>
            The arguments for run method.
        kwargs: dict<Any>
            The key word arguments for run method.

        Returns
        -------
        plan or tensot:
           The plan generated by method or processed tensor.
        """

        method, config = self.get_executor()
        kwargs.update({k: v for k, v in config.items() if k not in kwargs})
        return method(*args, **kwargs)

    def change_stage(self, stage: str):
        """Change the stage of strategy"""

        self._stage = stage

    def add_executor(self, stage: str, method: callable, config: dict):
        """Add a executor to strategy

        Parameters
        ----------
        stage: str
            The mark of the executor
        method: callable
            The method to process tensor.
        method_config: dict
            The method config.
        """

        self._executors[stage] = (method, config)
        if not self._stage:
            self._stage = stage

    def get_executor(self) -> Tuple[callable, dict]:
        """Get executor of current stage

        Returns
        -------
        executor: tuple<callable, dict>
           The method and config to execute strategy
        """

        if self._stage in self._executors:
            return self._executors[self._stage]
        return self._executors["default"]

    def get_config(self, key: str, default: Any) -> Any:
        """Get the value in config"""

        return self.get_executor()[1].get(key, default)

    def copy(
        self,
        name: str = None,
        stage: str = None,
        methods: Dict[str, callable] = None,
        configs: Dict[str, dict] = None,
    ):
        """Copy a strategy

        Parameters
        ----------
        name: str
            The name for new strategy
        stage: str
            The init stage for new strategy
        methods: dict<str, callable>
            The methods of new executors.
        configs: dict<str,dict>
            The method config of new executors.

        Returns
        -------
        new_strategy: Strategy
           The copied strategy
        """

        methods = methods or {}
        configs = configs or {}
        strategy = Strategy(name or self._name, stage or self._stage)
        for st_name, (method, config) in self._executors.items():
            new_method = methods.get(st_name, method)
            new_config = configs.get(st_name, {})
            new_config.update({k: v for k, v in config.items() if k not in new_config})
            strategy.add_executor(st_name, new_method, new_config)
        return strategy


class BaseTool(object):
    """Basic tool of MSC

    Parameters
    ----------
    stage: str
        The stage of tool
    plan_file: str
        The plan file path.
    strategys: list[dict]
        The strategys of the tool.
    workspace: MSCDirectory
        The workspace of the tool.
    options: dict
        The extra options for the tool
    verbose_step: int
        The verbose interval step.
    logger: logging.Logger
        The logger
    """

    def __init__(
        self,
        stage: str,
        plan_file: str,
        strategys: dict,
        options: dict = None,
        verbose_step: int = 50,
        logger: logging.Logger = None,
    ):
        self._stage = stage
        if os.path.isfile(plan_file):
            self._plan = msc_utils.load_dict(plan_file)
        else:
            self._plan = {}
        self._strategys = self._parse_strategys(msc_utils.copy_dict(strategys))
        self._options = options or {}
        self._verbose_step = verbose_step
        self._logger = logger or msc_utils.get_global_logger()
        title = "{}.SETUP({} @ {})".format(self.tool_type().upper(), self._stage, self.framework())
        self._logger.info(msc_utils.msg_block(title, self.setup(), width=0))

    def setup(self) -> dict:
        """Setup the tool

        Returns
        -------
        info: dict
            The setup info.
        """

        self._tensor_cache = {}
        self._enabled, self._is_training = True, True
        self._graphs, self._weights = [], {}
        self._graph_id, self._forward_cnt = 0, 0
        return {
            "style": self.tool_style(),
            "strategys": {k: v.inspect() for k, v in self._strategys.items()},
            "options": self._options,
            "verbose_step": self._verbose_step,
            "planed_num": len(self._plan),
        }

    def reset(
        self,
        graphs: List[MSCGraph],
        weights: List[Dict[str, tvm.nd.array]],
        cache_dir: msc_utils.MSCDirectory = None,
    ) -> Tuple[List[MSCGraph], List[Dict[str, tvm.nd.array]]]:
        """Reset the tool with graphs and weights

        Parameters
        ----------
        graphs: list<MSCgraph>
            The msc graphs.
        weights: list<dic<str, tvm.nd.array>>
            The weights
        cache_dir: MSCDirectory
            cache path for save/load info

        Returns
        -------
        graphs: list<MSCgraph>
            The msc graphs.
        weights: list<dic<str, tvm.nd.array>>
            The weights
        """

        self._forward_cnt = 0
        self._tensor_cache = {}
        if cache_dir and os.path.isfile(cache_dir.relpath("cache_info.json")):
            cache_info = msc_utils.load_dict(cache_dir.relpath("cache_info.json"))
            self.load_cache(cache_dir, cache_info)
        else:
            graphs, weights = self.load_graphs(graphs, weights)
        self._graphs, self._weights = graphs, {}
        for sub_weights in weights:
            self._weights.update(sub_weights)
        return self._graphs, weights

    def change_stage(self, stage: str):
        """Change the stage of tools and strategy"""

        self._stage = stage
        for strategy in self._strategys.values():
            strategy.change_stage(stage)

    def destory(self):
        """Destory tool"""

        self._graphs, self._weights = [], {}

    def load_graphs(
        self, graphs: List[MSCGraph], weights: List[Dict[str, tvm.nd.array]]
    ) -> Tuple[List[MSCGraph], List[Dict[str, tvm.nd.array]]]:
        """Load the graphs and weights

        Parameters
        ----------
        graphs: list<MSCgraph>
            The msc graphs.
        weights: list<dic<str, tvm.nd.array>>
            The weights

        Returns
        -------
        graphs: list<MSCgraph>
            The msc graphs.
        weights: list<dic<str, tvm.nd.array>>
            The weights
        """

        return graphs, weights

    def execute_before_build(self, *args, **kwargs):
        """Execute before model build

        Parameters
        ----------
        args: list<Any>
            The arguments for model build.
        kwargs: dict<Any>
            The key word arguments for model build.
        """

        if self._enabled:
            self._graph_id = self._infer_graph_id(kwargs)
            self._logger.debug(
                "%s.before_build(%s) graph[%d](%s)",
                self.tool_type().upper(),
                self._stage,
                self._graph_id,
                "train" if self._is_training else "eval",
            )
            return self._execute_before_build(*args, **kwargs)
        return None

    def _execute_before_build(self, *args, **kwargs):
        """Execute before model build

        Parameters
        ----------
        args: list<Any>
            The arguments for model build.
        kwargs: dict<Any>
            The key word arguments for model build.
        """

        return None

    def execute_after_build(self, output: Any) -> Any:
        """Execute after model build

        Parameters
        ----------
        output: Any
            The output reference of the model.

        Returns
        -------
        output: Any
           The modified output reference.
        """

        if self._enabled:
            output = self._execute_after_build(output)
            self._logger.debug(
                "%s.after_build(%s) graph[%d](%s)",
                self.tool_type().upper(),
                self._stage,
                self._graph_id,
                "train" if self._is_training else "eval",
            )
        return output

    def _execute_after_build(self, output: Any) -> Any:
        """Execute after model build

        Parameters
        ----------
        output: Any
            The output reference of the model.

        Returns
        -------
        output: Any
           The modified output reference.
        """

        return output

    def execute_before_forward(self, *args, **kwargs):
        """Execute before model forward

        Parameters
        ----------
        args: list<Any>
            The arguments for model forward.
        kwargs: dict<Any>
            The key word arguments for model forward.
        """

        if self._enabled:
            self._graph_id = self._infer_graph_id(kwargs)
            if self.should_log():
                self._logger.debug(
                    "%s.before_forward[%d](%s) for graph[%d]",
                    self.tool_type().upper(),
                    self._forward_cnt,
                    self._stage,
                    self._graph_id,
                )
            return self._execute_before_forward(*args, **kwargs)
        return None

    def _execute_before_forward(self, *args, **kwargs):
        """Execute before model forward

        Parameters
        ----------
        args: list<Any>
            The arguments for model forward.
        kwargs: dict<Any>
            The key word arguments for model forward.
        """

        return None

    def execute_after_forward(self, output: Any) -> Any:
        """Execute after model forward

        Parameters
        ----------
        output: Any
            The output reference of the model.

        Returns
        -------
        output: Any
           The modified output reference.
        """

        if self._enabled:
            output = self._execute_after_forward(output)
            if self.should_log():
                self._logger.debug(
                    "%s.after_forward[%d](%s) for graph[%d]",
                    self.tool_type().upper(),
                    self._forward_cnt,
                    self._stage,
                    self._graph_id,
                )
            self._forward_cnt += 1
        return output

    def _execute_after_forward(self, output: Any) -> Any:
        """Execute after model forward

        Parameters
        ----------
        output: Any
            The output reference of the model.

        Returns
        -------
        output: Any
           The modified output reference.
        """

        return output

    def process_tensor(self, tensor: Any, name: str, consumer: str, scope: str) -> Any:
        """Process tensor

        Parameters
        -------
        tensor: Any
            Tensor in framework
        name: str
            The name of the tensor.
        consumer: str
            The name of the consumer.
        scope: str
            The scope mark teacher| student| null

        Returns
        -------
        tensor: Any
            The processed tensor.
        """

        if not self._support_scope(scope):
            return tensor
        process = self._get_tensor_cache(name, consumer, "process")
        if process is None:
            process = self._check_tensor(name, consumer)
            self._save_tensor_cache(name, consumer, "process", process)
        if not process:
            return tensor
        strategy = self._get_tensor_strategy(name, consumer)
        return self._process_tensor(tensor, name, consumer, strategy)

    def _support_scope(self, scope: str) -> bool:
        """Check if the scope si supported

        Parameters
        -------
        scope: str
            The scope mark teacher| student| null

        Returns
        -------
        vaild: bool
            Whether to process the tensor.
        """

        return True

    def _check_tensor(self, name: str, consumer: str) -> bool:
        """Check if the tensor should be processed

        Parameters
        -------
        name: str
            The name of the tensor.
        consumer: str
            The name of the consumer.

        Returns
        -------
        vaild: bool
            Whether to process the tensor.
        """

        strategy = self._get_tensor_strategy(name, consumer)
        return strategy is not None

    def _process_tensor(self, tensor: Any, name: str, consumer: str, strategy: Strategy) -> Any:
        """Process tensor

        Parameters
        -------
        tensor: Any
            Tensor in framework
        name: str
            The name of the tensor.
        consumer: str
            The name of the consumer.
        strategy: Strategy
            The strategy for the tensor

        Returns
        -------
        tensor: Any
            The processed tensor.
        """

        return tensor

    def load_cache(self, cache_dir: msc_utils.MSCDirectory, cache_info: dict):
        """Save runner to cache

        Parameters
        -------
        cache_dir: MSCDirectory
            cache path for save/load info
        cache_info: dict
            The cache_info
        """

        return None

    def save_cache(self, cache_dir: msc_utils.MSCDirectory) -> dict:
        """Save runner to cache

        Parameters
        -------
        cache_dir: MSCDirectory
            cache path for save/load info

        Returns
        -------
        cache_info: dict
            The cache_info.
        """

        return {}

    def visualize(self, visual_dir: msc_utils.MSCDirectory):
        """Visualize MSCGraphs

        Parameters
        -------
        visual_dir: MSCDirectory
            Visualize path for saving graph
        """

        return None

    def update_plan(self, plan: dict):
        """Update the plan

        Parameters
        ----------
        plan: dict
            The new plan.
        """

        self._plan.update(plan)

    def get_plan(self, name: str) -> dict:
        """Get the plan for name

        Parameters
        ----------
        name: str
            The plan name.

        Returns
        -------
        plan: dict
            The plan of the name.
        """

        return self._plan.get(name, {})

    def finalize(self) -> dict:
        """Get the plan"""

        if self._plan:
            self._logger.info(
                "%s(%s) plan %d tensors", self.tool_type().upper(), self._stage, len(self._plan)
            )
        return self._plan

    def enable(self):
        """Enable the tool"""

        self._enabled = True

    def disable(self):
        """Disable the tool"""

        self._enabled = False

    def train(self):
        """Set the tool to train mode"""

        self._is_training = True

    def eval(self):
        """Set the tool to eval mode"""

        self._is_training = False

    def to_tensor_id(self, name: str, consumer: str) -> str:
        """Concat name to unique id

        Parameters
        ----------
        name: str
            The name of tensor.
        consumer: str
            The name of consumer.

        Returns
        -------
        tensor_id: str
           The unique name of edge.
        """

        return "{}-c-{}".format(name, consumer)

    def from_tensor_id(self, tensor_id: str) -> Tuple[str]:
        """Split name from unique id

        Parameters
        ----------
        tensor_id: str
           The unique name of edge.

        Returns
        -------
        name: str
            The name of tensor.
        consumer: str
            The name of consumer.
        """

        return tensor_id.split("-c-")

    def is_weight(self, name: str) -> bool:
        """Check if the tensor is weight

        Parameters
        ----------
        name: str
           The name of tensor.

        Returns
        -------
        is_weight: bool
            Whether the name is weight.
        """

        return name in self._weights

    def should_log(self) -> bool:
        """Check if should log

        Returns
        -------
        should_log: bool
           Whether should log.
        """

        return self._forward_cnt % self._verbose_step == 0

    def _infer_graph_id(self, kwargs: dict) -> int:
        """Infer graph id from kwargs

        Parameters
        ----------
        kwargs: dict
           The kwargs for execute.
        """

        if "graph_id" in kwargs:
            return kwargs.pop("graph_id")
        if "graph_name" in kwargs:
            name = kwargs.pop("graph_name")
            for idx, g in enumerate(self._graphs):
                if g.name == name:
                    return idx
        return 0

    def get_nodes(self) -> Iterable[MSCJoint]:
        """Get all the nodes in the graphs.

        Returns
        -------
        nodes: generator<MSCJoint>
            The generator of nodes.
        """

        for g in self._graphs:
            for n in g.get_nodes():
                yield n

    def find_node(self, name: str) -> MSCJoint:
        """Find node by name.

        Parameters
        ----------
        name: string
            The name of the node.

        Returns
        -------
        node: MSCJoint
            The found node.
        """

        for g in self._graphs:
            if g.has_node(name):
                return g.find_node(name)
        raise Exception("Can not find node {} from graphs".format(name))

    def find_tensor(self, name: str) -> MSCTensor:
        """Find tensor by name.

        Parameters
        ----------
        name: string
            The name of the tensor.

        Returns
        -------
        node: MSCTensor
            The found tensor.
        """

        for g in self._graphs:
            if g.has_tensor(name):
                return g.find_tensor(name)
        raise Exception("Can not find tensor {} from graphs".format(name))

    def find_producer(self, name: str) -> MSCJoint:
        """Find producer by tensor_name .

        Parameters
        ----------
        name: string
            The name of the tensor.

        Returns
        -------
        node: MSCJoint
            The found prducer.
        """

        for g in self._graphs:
            if g.has_tensor(name):
                return g.find_producer(name)
        raise Exception("Can not find producer of {} from graphs".format(name))

    def find_consumers(self, name: str) -> List[MSCJoint]:
        """Find consumers by tensor_name.

        Parameters
        ----------
        name: string
            The name of the tensor.

        Returns
        -------
        node: list<MSCJoint>
            The found consumers.
        """

        for g in self._graphs:
            if g.has_tensor(name):
                return g.find_consumers(name)
        raise Exception("Can not find consumers of {} from graphs".format(name))

    def get_data(self, name: str) -> np.ndarray:
        """Get the data by name

        Parameters
        -------
        name: str
            The tensor name

        Returns
        -------
        data: np.ndarray
            The data.
        """

        if name in self._weights:
            return msc_utils.cast_array(self._weights[name])
        raise Exception("Can not find data " + str(name))

    def _parse_strategys(self, strategy_list: dict):
        """Parse the strategy to get valid strategy

        Parameters
        -------
        strategy_list: dict
            The given strategy

        Returns
        -------
        strategys: dict<str, Strategy>
            The parsed strategy.
        """

        strategys = {}
        assert isinstance(strategy_list, list) and all(
            isinstance(s, dict) for s in strategy_list
        ), "Strategy should be given as list of dict"
        for stra in strategy_list:
            method_cls_name = stra.pop("method_cls") if "method_cls" in stra else "default"
            method_cls = msc_utils.get_registered_tool_method(
                self.framework(), self.tool_type(), method_cls_name
            )
            default_cls = msc_utils.get_registered_tool_method(
                MSCFramework.MSC, self.tool_type(), method_cls_name
            )
            method = stra.pop("method") if "method" in stra else "default"
            method = (
                getattr(method_cls, method)
                if hasattr(method_cls, method)
                else getattr(default_cls, method)
            )
            stage = stra.pop("stage") if "stage" in stra else "default"
            if "op_types" in stra:
                op_types = stra.pop("op_types")
                if "tensor_types" in stra:
                    tensor_types = stra.pop("tensor_types")
                else:
                    tensor_types = ["input", "output", "weight"]
                for s_type, t_type in product(op_types, tensor_types):
                    mark = "{}.{}".format(s_type, t_type)
                    if mark not in strategys:
                        strategys[mark] = Strategy(mark, self._stage)
                    strategys[mark].add_executor(stage, method, copy.deepcopy(stra))
            elif "op_names" in stra:
                op_names = stra.pop("op_names")
                if "tensor_types" in stra:
                    tensor_types = stra.pop("tensor_types")
                else:
                    tensor_types = ["input", "output", "weight"]
                for s_name, t_type in product(op_names, tensor_types):
                    mark = "{}.{}".format(s_name, t_type)
                    if mark not in strategys:
                        strategys[mark] = Strategy(mark, self._stage)
                    strategys[mark].add_executor(stage, method, copy.deepcopy(stra))
            else:
                if "default" not in strategys:
                    strategys["default"] = Strategy("default", self._stage)
                strategys["default"].add_executor(stage, method, copy.deepcopy(stra))
        return strategys

    def _save_tensor_cache(self, name: str, consumer: str, key: str, value: Any):
        """Save the data to tensor cache

        Parameters
        -------
        name: str
            The tensor name.
        consumer: str
            The name of the consumer.
        key: str
            The data key.
        value: any
            The value to cache.
        """

        tensor_id = self.to_tensor_id(name, consumer)
        if tensor_id not in self._tensor_cache:
            self._tensor_cache[tensor_id] = {}
        self._tensor_cache[tensor_id][key] = value

    def _get_tensor_cache(self, name: str, consumer: str, key: str) -> Any:
        """Get the cached tensor data

        Parameters
        -------
        name: str
            The tensor name.
        consumer: str
            The name of the consumer.
        key: str
            The data key.

        Returns
        -------
        value: any
            The cached value.
        """

        tensor_id = self.to_tensor_id(name, consumer)
        if tensor_id not in self._tensor_cache:
            return None
        return self._tensor_cache[tensor_id].get(key)

    def _get_tensor_strategy(self, name: str, consumer: str) -> dict:
        """Get the method by name

        Parameters
        -------
        name: str
            The tensor name.
        consumer: str
            The name of the consumer.

        Returns
        -------
        method: callable
            The method.
        """

        tensor_id = self.to_tensor_id(name, consumer)
        if "strategy" not in self._tensor_cache.get(tensor_id, {}):
            if self.is_weight(name):
                consumer = self.find_node(consumer)
                name_refs = [consumer.name + ".weight", consumer.optype + ".weight"]
            elif consumer == "exit":
                producer = self.find_producer(name)
                name_refs = [producer.name + ".output", producer.optype + ".output"]
            else:
                consumer = self.find_node(consumer)
                producer = self.find_producer(name)
                name_refs = [
                    consumer.name + ".input",
                    consumer.optype + ".input",
                    producer.name + ".output",
                    producer.optype + ".output",
                ]
            strategy = None
            for n in name_refs:
                if n in self._strategys:
                    strategy = self._strategys[n]
                    break
            strategy = strategy or self._strategys.get("default")
            self._save_tensor_cache(name, consumer, "strategy", strategy)
        return self._get_tensor_cache(name, consumer, "strategy")

    @classmethod
    def tool_type(cls):
        return ToolType.BASE

    @classmethod
    def framework(cls):
        return MSCFramework.MSC

    @classmethod
    def tool_style(cls):
        return "base"
